## Introduction to fixed / random effects 

We will need to know :
    - what is the variance of a linear combinaison of variables
    - play with the kroneker product
    - look at scipy.stat module

### First, checkout pna2015 and create your own day14 branch

### Variance of linear combinaison

Let's $\textbf{y}$ for instance the value of a voxel in an fmri image) be our variable. If we repeat the experiment, we will observe $y_1, y_2, ..$. $\textbf{y}$ could also be the value of a contrast for a given subject, and we observe multiple subjects. 


Let's $\textbf{z}$ be another variable. 

Computing the variance (or, estimating the variance) of $\textbf{y}$ or $\textbf{z}$ necessitate that we have several observations.

The variance is defined as the true mean of the squared deviation of the observation to the true mean of the data. We need to estimate this. 

First, we estimate the mean : $\bar{y} = \frac{1}{n}\sum_i^n{y_i}$
Second we estimate the variation around this mean: 

$$ \widehat{\textrm{Var}}(\textbf{y}) = \frac{1}{n}\sum_i^n{(y_i - \bar{y})}^2$$

Notice again that this is just an estimation. The true variance is a fixed number, but we will get a different answer each time we have a different dataset. 

Now, we can show that:

$$ \textrm{Var}(\textbf{y} + \textbf{z}) = \textrm{Var}(\textbf{y}) + \textrm{Var}(\textbf{z}) + 2\textrm{Cov}(\textbf{y},\textbf{z})
$$

and that

$$ \textrm{Var}(a \, \textbf{y}) = a^2 \textrm{Var}(\textbf{y}) $$

In [1]:
import numpy as np

In [2]:
one_matrix = np.asarray([[2, 3],[4,1]])
the_identity = np.eye(2)

In [3]:
K = np.kron(the_identity, one_matrix)

In [4]:
one_matrix

array([[2, 3],
       [4, 1]])

In [5]:
the_identity

array([[ 1.,  0.],
       [ 0.,  1.]])

In [6]:
K


array([[ 2.,  3.,  0.,  0.],
       [ 4.,  1.,  0.,  0.],
       [ 0.,  0.,  2.,  3.],
       [ 0.,  0.,  4.,  1.]])

In [7]:
c = np.array([1, -1, 0, 0 ])
o = np.ones((3))
k = np.kron(o, c)

In [8]:
k

array([ 1., -1.,  0.,  0.,  1., -1.,  0.,  0.,  1., -1.,  0.,  0.])

In [9]:
o

array([ 1.,  1.,  1.])